-- MySQL Script generated by MySQL Workbench
-- Mon Apr 19 13:57:35 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema products_orm
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema products_orm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `products_orm` DEFAULT CHARACTER SET utf8 ;
USE `products_orm` ;

-- -----------------------------------------------------
-- Table `products_orm`.`manufacturers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `products_orm`.`manufacturers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `products_orm`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `products_orm`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `manufacturer_id` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  `description` VARCHAR(255) NULL,
  `price` VARCHAR(45) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_products_manufacturers_idx` (`manufacturer_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_manufacturers`
    FOREIGN KEY (`manufacturer_id`)
    REFERENCES `products_orm`.`manufacturers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
